apiVersion: v1
kind: Service
metadata:
  name: petclinic-svc
  namespace: petclinic
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: petclinic-svc
  ports:
  - name: http
    port: 80
    targetPort: 80
